name: Deploy Aureolux theme to Arsys

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get update -y && sudo apt-get -y install lftp

      - name: Upload via FTPS
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          lftp -c "
            set ftp:ssl-allow true;
            open -u $FTP_USER,$FTP_PASS $FTP_HOST;
            mirror -R --delete --verbose \
              ./wp-content/themes/aureolux \
              /html/wp-content/themes/aureolux
          "

